# 程序基本配置
project:
  listeningPort: 7777  # 监听端口号
  port: 7777
  portFile: "Project.sock"
  name: "USDTPAY"
  limitIp: 2
  ThreeUrl: "http://139.180.130.69"
  RechargingJumpAddress: "https://usdt.sssdk.xyz/static/pay/#/"
  ApiKey: "6e347830f78d544jshsjld177f7278fb8"
  OrderEffectivityTime: 250000  #秒 普通订单过期时间

#日志
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 300  #每个人日志文件大小
  max_age: 30    #存储天数
  max_backups: 7 #备份数量

#数据库 配置
#mysql:
#  host: "127.0.0.1"
#  port: "3306"
#  user: "root"
#  password: "123456789"
#  dbname: "paymentplatform"

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "paymentplatform"
  password: "paymentplatform"
  dbname: "paymentplatform"

#redis  配置
redis:
  host: "127.0.0.1"
  port: 6379
  db: 9
  password: ""
  pool_size: 20